{{- if and (.Values.cassandra) (.Values.cassandra.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cassandra.applicationName }}
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: networking.k8s.io
    kind: NetworkPolicy
    jsonPointers:
    - /spec/egress
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ required "repoUrl value is required" .Values.repoUrl }}
    path: {{ .Values.clusterName }}/edr-workloads/{{ .Values.cassandra.applicationName }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.clusterName }}{{ .Values.cassandra.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace={{ .Values.cassandra.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  {{- end -}}
