{{- if and (.Values.streamexport) (.Values.streamexport.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.streamexport.applicationName }}
  namespace: {{ .Values.argoNamespace | default "argocd" }}
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ required "repoUrl value is required" .Values.repoUrl }}
    path: {{ .Values.clusterName }}/edr-workloads/{{ .Values.streamexport.applicationName }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.clusterName }}-{{ .Values.streamexport.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace={{ .Values.streamexport.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  {{- end -}}
