---
name: Push
on:
  push:
    branches:
    - master

jobs:
  on_push:
    name: on_push
    uses: trellix-edr/smart-pipeline-cd/.github/workflows/template_on_push.yaml@v1.4
    with:
      remote_branch: master
      smart_pipeline_cd_ref: v1.4
      auto_sync_envs: "edrpreprod edrusw edruse edrcac edraps edreuc edrind"
      timeout: 900
    secrets:
      remote_token: ${{secrets.SVC_GITHUB_COM_TOKEN}}
      token: ${{secrets.SVC_GITHUB_TOKEN}}
      argocd_username: ${{secrets.ARGOCD_SYNC_USERNAME}}
      argocd_password: ${{secrets.ARGOCD_SYNC_PASSWORD}}
      google_chat_webhook_url: ${{secrets.GOOGLE_CHAT_WEBHOOK_URL}}
